version: '3.8'

services:
  frontend:
    image: cezarpop/walkingskeleton1_foodconnect:frontend
    ports:
      - "3000:80"
    # depends_on:
    #   - chat
    #   - signup
    #   - email

  chat:
    image: cezarpop/walkingskeleton1_foodconnect:chat-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.localhost`) && PathPrefix(`/chat`)"
 

  signup:
    image: cezarpop/walkingskeleton1_foodconnect:signup-service
    ports:
      - "8082:8082"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.signup.rule=Host(`signup.localhost`) && PathPrefix(`/signUp`)"

  email:
    image: cezarpop/walkingskeleton1_foodconnect:email-service
    ports:
      - "8081:8081"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  rabbitmq:
    image: rabbitmq:3.13.1-management
    ports:
      - "15672:15672"
      # - "5672:5672"

  traefik:
    image: traefik:v3.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  mongodb-data: