name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        run: sonar-scanner \
          -Dsonar.projectKey=Cezarpop12_SignUp-WS1 \
          -Dsonar.organization=cezarpop12 \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=93efab0926273cd447dc450f56b19e281649b78b
        env:
          SONAR_TOKEN: ${{ secrets.Sonar }}
