name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Start the Application
        run: |
          docker-compose up -d
        # Since the docker-compose.yml file is now in the root of the repository

      - name: Wait for the application to be ready
        run: sleep 60
        # Adjust the sleep time if needed to ensure your application is up and running

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --network="host" -v $(pwd):/zap/wrk/:rw -t securecodebox/zap /zap/zap-baseline.py -t http://localhost:3000 -r /zap/wrk/zap_report.html
        # Replace "http://localhost:3000" with the actual URL and port of your application

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Report
          path: zap_report.html
        # Ensure the correct path to your zap_report.html
